<table>
    <tr>
        <th>Movie Name</th>
        <th>Director</th>
        <th>Actor</th>
    </tr>
    <?php
    $movie = $block->getProductCollection();
    $movie->getData();
    foreach ($movie as $item): ?>
    $a=1;
    <tr>
        <td><?php echo $item->getMovie();?></td>
        <td><?php echo $item->getDirector();?></td>
        <td><?php echo $item->getActor();?></td>
    </tr>
    <?php endforeach;?>

</table>
